apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  PG_PASSWORD: password
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "postgres"
  PORT: "3000"
  RUN_MIGRATIONS: "true"
